### ISSUE TITLE
Reassign user role of expired users on migration start

### ISSUE THREAD

**Issue by twoldrich** [laterpay/laterpay-wordpress-subscriber-migrator#11]
On our customer's system, all registered users (even the ones with already expired subscriptions) have the same "subscriber" user role. That means, giving full access to this user role would also give those "expired" subscribers unlimited access and (as we currently ignore expired subscriptions in the csv according to @AliaksandrVahura-ScienceSoft), we will never unassign them from this subscription user role.

That's why, we have to unassign **all users with already expired subscriptions** from their current user role and assign them to a new one, **when the migration is started**.

@drdla Fine for you?  @AliaksandrVahura-ScienceSoft Did I correctly rephrase your proposal?

**Comment by drdla** [comment]
I think that should be done manually and not automatically by our plugin
