### ISSUE TITLE
Add WordPress pointer on activation of plugin

### ISSUE THREAD

**Issue by drdla** [laterpay/laterpay-wordpress-subscriber-migrator#2]
We should have a pointer pointing at the LaterPay entry in the WordPress backend menu (just like the ADMIN_MENU_POINTER in the laterpay plugin) to notify the user how he has to proceed after activating the migrator plugin.

**Heading**
"Subscriber Migration plugin activated"

**Content**
"The tab "Migration" has been added to the LaterPay plugin backend. You can configure and manage the subscriber migration process from there."

**Comment by avahura** [comment]
@drdla Done. Please check.
