### ISSUE TITLE
Make plugin compatible with PHP 5.2.4

### ISSUE THREAD

**Issue by drdla** [laterpay/laterpay-wordpress-subscriber-migrator#9]

**Comment by avahura** [comment]
Workaround added of unsupported features: added workarounds for the composer autoload and for the str_getcsv function. Now plugin should be compatible with 5.2.4.

**Comment by avahura** [comment]
@drdla @twoldrich Will be great to test it on 5.2.4 env but from my point of view all should work ok now.

**Comment by drdla** [comment]
Tested with phpci and confirmed to be compatible.
